on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: 1.14.x
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build application
      run: gomvc application api
    - name: Add resource
      run: gomvc resource pants