name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    strategy:
      fail-fast: true
      matrix:
        # Locked at https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
        os:
        - ubuntu-18.04
        - windows-2019
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v ./...

    - name: Install dependencies
      run: go get golang.org/x/tools/cmd/goimports

    - name: Setup test directory
      run: mkdir test

    - name: Generate application
      run: go run cmd/gomvc/main.go application test-api --dest ./test

    - name: Add resource
      run: go run cmd/gomvc/main.go resource gophers --dest ./test
